---

- name: Assert that the role is executed on a supported platform
  ansible.builtin.assert:
    that:
      - (ansible_distribution_major_version | int) > 7
      - ansible_distribution_file_variety == 'RedHat'
    msg: 'This role only supports Enterprise Linux version 7 or greater.'
    quiet: true

- name: Include variables specific for the distribution.
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"

- name: Include install tasks.
  ansible.builtin.import_tasks:
    file: install.yml

- name: Include configure tasks.
  ansible.builtin.import_tasks:
    file: configure.yml

- name: Include firewall tasks.
  ansible.builtin.import_tasks:
    file: firewall.yml
  when: ansible_role_cassandra_manage_firewalld

- name: Enable and start Apache Cassandra service.
  ansible.builtin.systemd:
    name: cassandra
    daemon_reload: true
    state: started
    enabled: true
  become: true
  register: cassandra_seeds_service_task
  when: inventory_hostname in ansible_role_cassandra_seeds

- name: Wait for Cassandra seed nodes to reach NORMAL state
  ansible.builtin.wait_for:
    path: /var/log/cassandra/system.log
    search_regex: "^INFO.*Node .* state jump to NORMAL$"
    delay: 10
  when:
    - inventory_hostname in ansible_role_cassandra_seeds
    - cassandra_seeds_service_task.changed or cassandra_config.changed

- name: Check for superuser creation.
  ansible.builtin.wait_for:
    path: /var/log/cassandra/system.log
    search_regex: ^INFO\s+\[OptionalTasks.*\]\s+.+CassandraRoleManager\.java:\d+\s+-\s+Created\sdefault\ssuperuser\srole\s'cassandra'$
    delay: 5
  register: waitfor
  when: cassandra_seeds_service_task.changed or cassandra_config.changed
  async: 60
  poll: 0
  ignore_errors: true

- name: Wait for any node to confirm superuser creation.
  ansible.builtin.async_status:
    jid: "{{ waitfor.ansible_job_id }}"
  register: job_result
  until: job_result.finished or job_result.failed
  retries: 10
  delay: 6
  when: waitfor.ansible_job_id is defined
  changed_when: false
  run_once: true

- name: Change password for the Cassandra user.
  ansible.builtin.command: cqlsh {{ ansible_role_cassandra_listen_address }} -u cassandra -p 'cassandra' {{'--ssl' if ansible_role_cassandra_ssl_enable }} -e "ALTER USER cassandra WITH PASSWORD '{{ ansible_role_cassandra_password }}';"
  when: inventory_hostname == play_hosts[0]
  environment:
    SSL_CERTFILE: '{{ ansible_role_cassandra_ssl_cert_dir }}/certificate.pem'
  no_log: true

- name: Include tasks to enable and start Cassandra service.
  ansible.builtin.include_tasks:
    file: service_start.yml
  loop: "{{ ansible_play_hosts_all }}"
  when:
    - cassandra_config.changed
    - inventory_hostname not in ansible_role_cassandra_seeds
